@isTest
public class Commissions_PayoutAdjBatchSch_Test{
    /**
    Global class Commissions_PayoutAdjBatchSch_Test {
        static testMethod void method1(){
            test.startTest();
            Commissions_PayoutAdjBatchSch sh1 = new Commissions_PayoutAdjBatchSch();      
            String sch = '0 0 23 * * ?';
            system.schedule('Test check', sch, sh1);
            Test.stopTest();
        }
    }
    **/
}