public with sharing class Commissions_Constants {
    //USER TEAMS
    public static final String BROKER_CONSULTANTS_TEAM = ' Broker Consultants Team';
    public static final String COLLECTION_TEAM = 'Collections Team';
    public static final String EVENTS_TEAM = 'Events Team';
    public static final String HYBRID_BROKER_COLLECTION_TEAM = 'Hybrid Broker Consultants Team';
    public static final String HYBRID_AGENT_TEAM = 'Hybrid Agent Team';
    public static final String NEW_BIZ_BROKER_Consultants = 'New Biz Broker Consultants';
    public static final String NEW_HIRE_TEAM = 'New Hire Team';
    public static final String BROKER_REGIONAL_DIRECTORS_TEAM = 'Broker Regional Directors Sales Team';
    public static final String RETENTION_TEAM = 'Retention Team';
    public static final String SCOTTSDALE_TERRITORY_TEAM = 'Scottsdale Territory Team';
    public static final String WEB_CHAT_TEAM = 'Web Chat Team';
    public static final String WLV_TERRITORY_TEAM  = 'WLV Territory Team';
    public static final String LEADS_TEAM = 'Leads Team ';
    public static final String WLV_SPECIAL_CAMPAIGN_SALES_TEAM = 'WLV Special Campaign Sales Team';
    public static final String MANAGERS_TEAM = 'Managers Team';
    public static final String COMMISSION_ACTIVE_STATUS = 'Active';
    public static final String COMMISSION_INACTIVE_STATUS = 'In Active';
    public static final String COLLECTION_PAST_DUE_TEAM = 'Collections Past Due Team';    
    public static final String COMMISSIONS_CLAWBACK = 'Clawback';
    public static final String NEW_SALE_WITHOUT_QUALIFIER = 'New Sale without Qualifier';
    public static final String NEW_SALE_WITH_QUALIFIER = 'New Sale with Qualifier';
    public static final String RENEWAL_WITHOUT_QUALIFIER = 'Renewal without Qualifier';
    public static final String RENEWAL_WITH_QUALIFIER = 'Renewal with Qualifier';
    
    public static final String CFCB_NEW_SALE_WITH_QUALIFIER = 'CFCB New Sale with Qualifier';
    public static final String CFCB_NEW_SALE_WITHOUT_QUALIFIER = 'CFCB New Sale without Qualifier';
    public static final String CFCB_NEW_RENEWAL_WITH_QUALIFIER = 'CFCB Renewal with Qualifier';
    public static final String CFCB_NEW_RENEWAL_WITHOUT_QUALIFIER = 'CFCB Renewal without Qualifier';
    public static final String ASSET_OWNER_COMPONENTS = 'Asset Owner Component';
    public static final String BROKER_REGIONAL_DIRECTORS_SALES_TEAM = 'Broker Regional Directors Sales Team';
    public static final String OPEN_SALE_COMPONENT = 'Open Sale Component';
    public static final String TIGER_LEAD_SALE = 'Tiger Lead Sale';
    public static final String PAYROLL_ADJUSTMENT= 'Payroll Adjustment';
    public static final String COLLECTIONS_CLIENT_RELATIONS_MANAGERS = 'Collections Client Relations Manager';
    public static final String OPEN_BOOK_COMPONENT = 'Open Book Component';
    public static final String APPROVAL_RECORD_TYPE = 'Approval Record Type';
    public static final String Other_Products_RECORD_TYPE = 'Other Products';
    public static final String CLIENT_RELATIONS_MANAGERS = 'Client Relations Manager';
    public Commissions_Constants(){}
    
}