// Name: RealSuiteComponentController_Test
// Description: Test Class for the Controller 'RealSuiteComponentController'
// Author: Pallavi Tammana

@IsTest
public class RealSuiteComponentController_Test{   
    static testMethod  void RealSuiteComponentController_Test(){
        test.starttest();
        RealSuiteComponentController obj = new RealSuiteComponentController();
        test.stoptest();        
    }
  }