@isTest
private class wwwMoveCom_Test{
    public static testMethod void main(){
        wwwMoveCom obj = new wwwMoveCom();
        wwwMoveCom.WaitListType obj1 = new wwwMoveCom.WaitListType();
        wwwMoveCom.request_element obj2 = new wwwMoveCom.request_element();
        wwwMoveCom.waitlist obj3 = new wwwMoveCom.waitlist();
        wwwMoveCom.params_element obj4 = new wwwMoveCom.params_element();
        wwwMoveCom.SyncWaitListRes_element obj5 = new wwwMoveCom.SyncWaitListRes_element();
    }
}